# Generated by Django 5.1.6 on 2025-03-05 15:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone_number',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid international format.Start with + and country code, followed by 1-14 digits.Example: +14155552671 or +911234567890', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='Primary phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondary_phone_number',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid international format.Start with + and country code, followed by 1-14 digits.Example: +14155552671 or +911234567890', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='Secondary phone number'),
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='platform')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
