# Generated by Django 5.1.6 on 2025-03-05 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='url'),
        ),
    ]
