# Generated by Django 5.1.6 on 2025-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, default=None, null=True, unique=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, default=None, null=True, unique=True, verbose_name='Designation'),
        ),
    ]
